# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3VOqbTGqOd85KREWqAio_eH0u5fGBCy
"""

from sklearn import datasets 
iris = datasets.load_iris()

from sklearn.model_selection import train_test_split
# separação da base em 20% de teste 80% de treino
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=4)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import numpy as np

k_range = range(1, 15)
scores = {}
scores_list = []

for k in k_range:
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(x_train, y_train)
  y_pred = knn.predict(x_test)
  scores[k] = metrics.accuracy_score(y_test, y_pred)
  scores_list.append(scores[k])

import matplotlib.pyplot as plt

plt.plot(k_range, scores_list)
plt.xlabel("Valor de K")
plt.ylabel("Acurácia")
plt.ylim(0.8, 1)
plt.title('Acurácia vs valor de K')